package com.example.happysentences

import android.os.Bundle
import android.speech.tts.TextToSpeech
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.platform.LocalContext
import java.util.Locale

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    HappySentencesScreen()
                }
            }
        }
    }
}

@Composable
private fun HappySentencesScreen() {
    val context = LocalContext.current

    var input by remember { mutableStateOf("") }
    var gentle by remember { mutableStateOf("") }
    var clear by remember { mutableStateOf("") }
    var brave by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }

    // TTS
    var tts by remember { mutableStateOf<TextToSpeech?>(null) }
    var ttsReady by remember { mutableStateOf(false) }

    DisposableEffect(Unit) {
        tts = TextToSpeech(context) { status ->
            if (status == TextToSpeech.SUCCESS) {
                tts?.language = Locale.KOREAN
                tts?.setSpeechRate(1.0f)
                ttsReady = true
            } else {
                ttsReady = false
            }
        }

        onDispose {
            tts?.stop()
            tts?.shutdown()
            tts = null
        }
    }

    fun briefInput(t: String, maxLen: Int = 32): String {
        val x = t.trim()
        if (x.length <= maxLen) return x
        // 단어 경계 비슷하게 처리(중간 잘림 최소화)
        val cut = x.lastIndexOf(' ', startIndex = maxLen).takeIf { it >= 8 } ?: maxLen
        return x.substring(0, cut).trim() + "…"
    }

    fun detectMood(t: String): String {
        val s = t.lowercase()
        return when {
            s.contains("짜증") || s.contains("화") || s.contains("열받") || s.contains("빡") -> "irritated"
            s.contains("불안") || s.contains("걱정") || s.contains("초조") -> "anxious"
            s.contains("우울") || s.contains("무기력") || s.contains("허무") -> "low"
            s.contains("외롭") || s.contains("쓸쓸") -> "lonely"
            s.contains("피곤") || s.contains("지쳤") || s.contains("힘들") -> "tired"
            s.contains("기대") || s.contains("설렘") || s.contains("좋아") || s.contains("기분") -> "good"
            s.contains("뿌듯") || s.contains("잘했") || s.contains("성공") -> "proud"
            else -> "neutral"
        }
    }

    fun generateLocally(text: String) {
        val trimmed = text.trim()
        if (trimmed.isEmpty()) return

        val mood = detectMood(trimmed)
        val brief = briefInput(trimmed)

        // ✅ 공감 프리픽스: 3줄 모두 공감으로 시작하게 강제
        val empath: String = when (mood) {
            "irritated" -> "짜증이 날 만한 상황이었네요."
            "anxious" -> "걱정이 올라올 만한 일이었네요."
            "tired" -> "오늘은 많이 지친 날이네요."
            "low" -> "기분이 가라앉을 만한 날이네요."
            "lonely" -> "혼자 버티는 느낌이 들 만한 날이네요."
            "good" -> "기분이 좋아진 이유가 분명히 있네요."
            "proud" -> "오늘 스스로 뿌듯할 만한 일이 있었네요."
            else -> "오늘 마음이 복잡해질 만했네요."
        }

        // ✅ 입력을 "그대로 끼워 넣는" 느낌을 줄이되, 내가 쓴 말이 반영되게 1번만 인용
        val quote = "\"$brief\""

        when (mood) {
            "good" -> {
                gentle = "$empath $quote 이런 순간은 그대로 즐겨도 됩니다."
                clear = "$empath 오늘 좋았던 포인트를 한 줄로만 남겨두면 더 오래 갑니다."
                brave = "$empath 내일도 비슷하게 기분 좋아질 수 있게, 쉬운 약속 1개만 정해볼까요?"
            }
            "irritated" -> {
                gentle = "$empath $quote 그럴 수 있습니다."
                clear = "$empath 그래서 지금은 판단을 미루고, 가장 작은 것부터 정리해도 됩니다."
                brave = "$empath 그래서 물 한 모금만 마시고, 할 일 1개만 적어보겠습니다."
            }
            "anxious" -> {
                gentle = "$empath $quote 지금은 숨부터 고르면 됩니다."
                clear = "$empath 그래서 '지금 할 수 있는 것'만 남기고, 나머지는 내일로 넘기겠습니다."
                brave = "$empath 그래서 가장 쉬운 1단계만 하겠습니다. 한 줄로 적고 하나만 하겠습니다."
            }
            "tired" -> {
                gentle = "$empath $quote 오늘은 스스로를 더 아껴도 됩니다."
                clear = "$empath 그래서 기준을 낮추고 '최소한'만 해도 충분합니다."
                brave = "$empath 그래서 30초만 쉬고, 다음 행동 1개만 정하겠습니다."
            }
            "low" -> {
                gentle = "$empath $quote 오늘은 작은 위로만 있어도 됩니다."
                clear = "$empath 그래서 '성과'보다 '유지'를 먼저 두겠습니다."
                brave = "$empath 그래서 아주 쉬운 것 1개만 하겠습니다. 창문을 열고 빛을 10초만 보겠습니다."
            }
            "lonely" -> {
                gentle = "$empath $quote 마음을 덜 몰아붙이겠습니다."
                clear = "$empath 그래서 해결보다 기록을 먼저 하겠습니다. 한 줄만 적어도 충분합니다."
                brave = "$empath 그래서 짧게 한 문장만 보내보겠습니다. 예: 오늘 좀 힘들었어요."
            }
            "proud" -> {
                gentle = "$empath $quote 스스로를 칭찬해도 됩니다."
                clear = "$empath 그래서 잘한 점을 한 줄로 남겨두겠습니다. 그 기록이 내일의 힘이 됩니다."
                brave = "$empath 그래서 작게 보상하겠습니다. 5분 쉬고 기분 좋게 마무리하겠습니다."
            }
            else -> {
                gentle = "$empath $quote 지금은 이 정도로도 충분합니다."
                clear = "$empath 그래서 순서를 정하겠습니다. '지금 할 수 있는 것'부터 하나씩 하겠습니다."
                brave = "$empath 그래서 가장 쉬운 것 1가지만 실행하겠습니다."
            }
        }

        isGenerated = true
    }

    fun speak(text: String) {
        val msg = text.trim()
        if (msg.isEmpty()) return
        if (!ttsReady) return
        tts?.speak(msg, TextToSpeech.QUEUE_FLUSH, null, "HS_TTS")
    }

    Scaffold { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 18.dp, vertical = 14.dp)
                .imePadding() // 키보드 올라올 때 가리지 않게
                .navigationBarsPadding() // 하단 네비게이션 바 영역 고려
        ) {
            Text(
                text = "😊 Happy Sentences",
                modifier = Modifier.fillMaxWidth(),
                textAlign = TextAlign.Center,
                style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold)
            )
            Text(
                text = "단어만 적어도 됩니다. 오늘 마음을 그대로 적어보세요.",
                modifier = Modifier.fillMaxWidth(),
                textAlign = TextAlign.Center,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )

            Spacer(Modifier.height(10.dp))

            // 기종별 화면 대응: 입력창 높이는 "최소/최대"만 주고, 나머지는 결과 영역이 가져가도록 함
            OutlinedTextField(
                value = input,
                onValueChange = { input = it },
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(min = 110.dp, max = 180.dp),
                placeholder = { Text("예: 내일은 어떤 일이 벌어질까 궁금해") },
                maxLines = 6
            )

            Spacer(Modifier.height(10.dp))

            Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                Button(
                    onClick = { generateLocally(input) },
                    enabled = input.trim().isNotEmpty()
                ) {
                    Text("행복문장 만들기")
                }

                OutlinedButton(
                    onClick = { if (isGenerated) speak(gentle) },
                    enabled = isGenerated && ttsReady
                ) {
                    Text("읽어주기")
                }

                TextButton(
                    onClick = {
                        input = ""
                        gentle = ""
                        clear = ""
                        brave = ""
                        isGenerated = false
                    }
                ) {
                    Text("초기화")
                }
            }

            Spacer(Modifier.height(10.dp))
            HorizontalDivider()
            Spacer(Modifier.height(10.dp))

            // ✅ 핵심: 결과 영역이 남은 공간을 차지하고(비율), 내부 스크롤(LazyColumn)로 끝까지 내려가게
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f), // 화면 크기마다 자동으로 결과 영역 높이 조절
                verticalArrangement = Arrangement.spacedBy(12.dp),
                contentPadding = PaddingValues(bottom = 28.dp) // 맨 아래 잘림 방지 여백
            ) {
                if (isGenerated) {
                    item {
                        Text("결과", style = MaterialTheme.typography.titleMedium)
                    }

                    item {
                        ResultCard(title = "다정한 한 줄", body = gentle, onSpeak = { speak(gentle) })
                    }
                    item {
                        ResultCard(title = "현실 정리 한 줄", body = clear, onSpeak = { speak(clear) })
                    }
                    item {
                        ResultCard(title = "용기 한 줄", body = brave, onSpeak = { speak(brave) })
                    }
                } else {
                    // 결과가 없을 때도 화면이 어색하지 않게 안내문
                    item {
                        Text(
                            text = "입력 후 '행복문장 만들기'를 눌러보세요.",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }

            if (!ttsReady) {
                Spacer(Modifier.height(8.dp))
                Text(
                    text = "음성 준비 중이거나 사용할 수 없습니다.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
        }
    }
}

@Composable
private fun ResultCard(
    title: String,
    body: String,
    onSpeak: () -> Unit
) {
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(
            modifier = Modifier.padding(14.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            Text(
                title,
                style = MaterialTheme.typography.titleSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            Text(body, style = MaterialTheme.typography.bodyLarge)
            Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                OutlinedButton(onClick = onSpeak) { Text("읽기") }
            }
        }
    }
}
